name: widgetbook
repository: https://github.com/widgetbook/widgetbook

packages:
  - packages/**
  - examples/**

command:
  version:
    linkToCommits: true
    branch: main
  bootstrap:
    usePubspecOverrides: true

scripts:
  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.
  pana:
    run: melos exec -c 10 -- "../../tool/verify_pub_score.sh"
    select-package:
      no-private: true
  get:
    run: melos exec --fail-fast -- "flutter clean && flutter pub get" 
    description: Checks if the package meets the pub.dev score requirement.